include(dependencies/hdf5.cmake)
include(dependencies/system_mpi.cmake)
include(dependencies/fortran_exceptions.cmake)
include(dependencies/hdf5_exceptions.cmake)
include(dependencies/lightda.cmake)
include(dependencies/lightda-lenkf-rsm.cmake)
